services:
  postgres:
    image: postgres:16
    container_name: student_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: student_api
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: student_backend
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: student_api
  
  frontend:
    build: ./frontend
    container_name: student_frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"

volumes:
  postgres_data: